In [16]:
import pandas as pd
population_df = pd.read_csv(r"C:\Users\38095\Documents\GitHub\Project_1_SO_week3\population.csv")
average_income_df = pd.read_csv(r"C:\Users\38095\Documents\GitHub\Project_1_SO_week3\income_state.csv")

In [19]:
p_ai_df = pd.concat([population_df, average_income_df], axis=1)
p_ai_df

             State  Population                 State Av_income
0          Alabama   5,108,468               Alabama    50,920
1           Alaska     733,406                Alaska    68,664
2          Arizona   7,431,344               Arizona    58,390
3         Arkansas   3,067,732              Arkansas    52,604
4       California  38,965,193            California    77,013
5         Colorado   5,877,610              Colorado    75,708
6      Connecticut   3,617,176           Connecticut    83,340
7         Delaware   1,031,890              Delaware    63,177
8          Florida  22,610,726  District of Columbia    96,092
9          Georgia  11,029,227               Florida    64,804
10          Hawaii   1,435,138               Georgia    56,588
11           Idaho   1,964,726                Hawaii    61,813
12        Illinois  12,549,689                 Idaho    56,615
13         Indiana   6,862,199              Illinois    67,653
14            Iowa   3,207,004               Indiana    58,329
15          Kansas   2,940,546                  Iowa    60,238
16        Kentucky   4,526,154                Kansas    60,433
17       Louisiana   4,573,749              Kentucky    51,929
18           Maine   1,395,722             Louisiana    54,527
19        Maryland   6,180,253                 Maine    60,425
20   Massachusetts   7,001,399              Maryland    70,236
21        Michigan  10,037,261         Massachusetts    84,551
22       Minnesota   5,737,915              Michigan    57,043
23     Mississippi   2,939,690             Minnesota    68,874
24        Missouri   6,196,156           Mississippi    46,388
25         Montana   1,132,812              Missouri    57,825
26        Nebraska   1,978,379               Montana    60,984
27          Nevada   3,194,176              Nebraska    64,263
28   New Hampshire   1,402,054                Nevada    62,092
29      New Jersey   9,290,841         New Hampshire    73,711
30      New Mexico   2,114,371            New Jersey    77,206
31        New York  19,571,216            New Mexico    52,190
32  North Carolina  10,835,491              New York    75,423
33    North Dakota     783,926        North Carolina    58,125
34            Ohio  11,785,935          North Dakota    70,391
35        Oklahoma   4,053,824                  Ohio    57,759
36          Oregon   4,233,358              Oklahoma    56,306
37    Pennsylvania  12,961,683                Oregon    62,314
38    Rhode Island   1,095,962          Pennsylvania    64,506
39  South Carolina   5,373,555          Rhode Island    63,551
40    South Dakota     919,318        South Carolina    53,615
41       Tennessee   7,126,489          South Dakota    68,173
42           Texas  30,503,301             Tennessee    58,311
43            Utah   3,417,734                 Texas    62,585
44         Vermont     647,464                  Utah    59,449
45        Virginia   8,715,698               Vermont    63,035
46      Washington   7,812,880              Virginia    69,021
47   West Virginia   1,770,071            Washington    75,345
48       Wisconsin   5,910,955         West Virginia    50,024
49         Wyoming     584,057             Wisconsin    61,496
50             NaN         NaN               Wyoming    73,216